global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']

  - job_name: 'ranking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8087']

  - job_name: 'rl-offer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8088']