server.port=8080
spring.kafka.bootstrap-servers=kafka:9092
server.address=0.0.0.0

# Prometheus Metrics Exposure
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.retargetiq=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n [%X{correlationId}]