server.port=8082

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/analytics_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Actuator + Prometheus Configuration
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

# Add service label to every metric (very important)
management.metrics.tags.application=retargetiq
management.metrics.tags.service=${spring.application.name}

# Enable percentiles for latency metrics
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.9,0.95,0.99

# Enable JVM + system metrics (for dashboards)
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true



# Logging
logging.level.com.example.analytics=DEBUG
logging.level.org.springframework.kafka=INFO


server.address=0.0.0.0

# ACTUATOR + PROMETHEUS
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always

management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=retargetiq
