spring.application.name=analytics-service

server.port=8084

server.address=0.0.0.0

############################################
# Kafka
############################################

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.consumer.group-id=analytics-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

############################################
# PostgreSQL
############################################

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/retargetdb}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:retarget}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:retarget}

spring.datasource.driver-class-name=org.postgresql.Driver

############################################
# JPA
############################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

############################################
# Prometheus
############################################

management.endpoints.web.exposure.include=health,prometheus,metrics,mappings

management.endpoint.prometheus.enabled=true

management.metrics.export.prometheus.enabled=true

############################################
# Logging
############################################

logging.level.root=INFO

logging.level.com.retargetiq=DEBUG